name: build_release

on: workflow_dispatch

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4

      - name: 安装依赖
        run: pnpm install

      - name: 执行构建
        run: pnpm run build

      - name: 读取版本号
        id: version
        run: |
          version=$(node -e "import('@gkd-kit/tools').then((m) => m.stdoutGkdVersion());")
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          echo "VERSION=${version}" >> "$GITHUB_ENV"

      - name: 提交构建产物到仓库
        id: commit
        run: |
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git config --local user.name github-actions[bot]
          git status
          git add .
          git commit -a -m "chore: v${{ env.VERSION }}"
        continue-on-error: true

      - name: 推送代码到远程仓库
        if: ${{ steps.commit.outcome == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
      
      - name: 临时生成用于离线导入的订阅文件
        run: |
          cp dist/gkd.json5 dist/gkd-Rules_v${{ env.VERSION }}.json5

      - name: 创建 GitHub 发布版本
        if: ${{ steps.commit.outcome == 'success' }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          body_path: ./dist/CHANGELOG.md
          generate_release_notes: true
          append_body: true
          files: |
            dist/gkd-Rules_v${{ env.VERSION }}.json5

      - name: 发布 NPM 包
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.commit.outcome == 'success' && env.NPM_TOKEN != '' }}
        run: |
          pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          node -e "import('@gkd-kit/tools').then((m) => m.updatePkgVersion());"
          pnpm publish --no-git-checks
          node -e "import('@gkd-kit/tools').then((m) => m.syncNpmmirror());"
