name: build_release

on: workflow_dispatch

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 配置 Node.js 运行环境
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 配置 pnpm 包管理器
        uses: pnpm/action-setup@v4

      - name: 安装项目依赖
        run: pnpm install

      - name: 构建项目
        run: pnpm run build

      - name: 生成版本号
        id: version
        run: |
          version=$(node -e "import('@gkd-kit/tools').then((m) => m.stdoutGkdVersion());")
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          echo "VERSION=${version}" >> "$GITHUB_ENV"

      - name: 提交构建产物
        id: commit
        run: |
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git config --local user.name github-actions[bot]
          git status
          git add .
          git commit -a -m "chore: v${{ env.VERSION }}"
        continue-on-error: true

      - name: 推送代码到远程仓库
        if: ${{ steps.commit.outcome == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
      
      - name: 生成离线订阅文件（用于发行版）
        run: |
          cp dist/gkd.json5 dist/gkd-rules-offline-id777-v${{ env.VERSION }}.json5

      - name: 创建 GitHub 发布版本
        if: ${{ steps.commit.outcome == 'success' }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          body_path: ./dist/CHANGELOG.md
          generate_release_notes: true
          append_body: true
          files: |
            dist/gkd-rules-offline-id777-v${{ env.VERSION }}.json5
